import Head from "next/head";

import styles from "./dev.module.css";
import { MainLink } from "@/components/MainLink/MainLink";

export default function Dev() {
  return (
    <>
      <Head>
        <title>Пик IT — разработчик</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=0.8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header>
          <h1 className={styles.job}>Может ты хочешь стать разработчиком?</h1>
        </header>
        <main>
          <p>
            В нашем телеграме рассказываем про курсы и делимся полезными материалами.
          </p>
        </main>
        <footer className={styles.footer}>
          <MainLink />
        </footer>
      </div>
    </>
  );
}
